[project]
name = "bubble-algorithm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nico-madruga", email = "nizinhoms@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
bubble-algorithm = "bubble_algorithm:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
